service:
  greeting: Hello from cone-prod
  
server:
port: 3004

spring:
  data:
    cassandra:
      keyspace-name: member_keyspace
      port: 9042
      contact-points: localhost
      username: cassandra
      password: cassandra
