service:
  greeting: Hello from cone global

server:
  port: 3003

spring:
  data:
    cassandra:
      keyspace-name: member_keyspace
      port: 9042
      contact-points: localhost
      username: cassandra
      password: cassandra
